### ISSUE TITLE
ReferenceError: logger is not defined

### ISSUE THREAD

**Issue by GiraffeSlacks** [lookback/meteor-logger#1]
Hi there,

I installed lookback:logger this morning and put the following code in `/client/etoeventSubmit.js`:

``` Javascript
Template.etoeventSubmit.events({
  'submit form': function (e) {
    e.preventDefault();

    var etoeventStart = roundToNearestQuarterHour(
      moment($(e.target).find('[name=etoeventStart]').val(), 'MM/DD/YYYY hh:mm a'));
    var etoeventStop = roundToNearestQuarterHour(
      moment($(e.target).find('[name=etoeventStop]').val(), 'MM/DD/YYYY hh:mm a'));

    myLogger.info('etoeventStart: ' + etoeventStart);
    myLogger.info('etoeventStop: ' + etoeventStop);

    // ...

});
```

I also made `/lib/environment.js` and it has the following:

``` Javascript
myLogger = logger({
  // Local logging. Defaults to true.
  local:  true,

  // Loggly options. Defaults to {}. If set, local logging will be disabled.
  loggly: {
    // Options to send to the Loggly npm module.
    logglyModuleOptions: {
      token:     '<token>',
      subdomain: '<subdomain>',
      json:      true
      },
      // Params to send to Loggly with every request.
      baseParams: {
        environment: 'development',   // Defaults to process.env.NODE_ENV
        serverName: '<workstation name>'
    }
  }
});
```

What am I doing wrong? I'm fairly new to Javascript, Loggly, and Meteor so please excuse any glaring oversight I've made.

**Comment by datacarl** [comment]
Hey @GiraffeSlacks 

Thanks for reporting this!

Currently the logger only operates on the server (since it's primarily used for reporting to loggly using the loggly npm module). That should probably be clarified in the docs.

I suppose loggly has support for client logging. If not, you could use a Meteor method to send the log data to the server which in turn reports it to loggly. Not sure if that's the best idea but it would work.

**Comment by GiraffeSlacks** [comment]
Hi @datacarl 

Thanks for the clarification and it's fine that it must be on the server because that's what I need! :)

My confusion came because I read "A global `Logger` object is automatically exported..." and stopped there. It's true that it's my fault but I can tell you that newbies find it very beneficial to be told where code should live. One way to do that, clearly, is by calling out a file path before your code snippet (similar to what I did in my original comment.)
